import os
import json
import argparse
import google.generativeai as genai

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--channel", required=True)
    parser.add_argument("--format", choices=["short", "long"], default="short")
    args = parser.parse_args()
    
    # Load the channel configuration
    with open(f"channels/{args.channel}.json", "r") as f:
        config = json.load(f)
        
    print(f"Generating video for: {config['channel_id']}")
    
    # Connect to Gemini API
    genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
    
    model = genai.GenerativeModel('gemini-3.5-flash-lite')
    
    print("Writing script...")
    response = model.generate_content(config["system_prompt"])
    
    # Clean and parse the JSON response from Gemini
    response_text = response.text.replace("```json", "").replace("```", "").strip()
    generated_data = json.loads(response_text)
    
    # Extract the script text
    script_text = generated_data.get("script_text", "This is an automated short generated by AgentTube.")
    
    # Save the title, description, and hashtags to metadata.json for Playwright
    metadata = {
        "title": generated_data.get("title", "New Video"),
        "description": generated_data.get("description", ""),
        "hashtags": generated_data.get("hashtags", "")
    }
    
    with open("metadata.json", "w", encoding="utf-8") as f:
        json.dump(metadata, f)
        
    print("Metadata saved successfully!")
    
    print("Generating voiceover...")
    # Clean quotes from the script to prevent command line syntax errors
    safe_script = script_text.replace('"', '\\"')
    os.system(f'edge-tts --text "{safe_script}" --write-media voice.mp3')
    
    print("Rendering video with FFmpeg...")
    # Generates a vertical video combining a black background and the voiceover
    output_file = f"{args.channel}_output.mp4"
    os.system(f'ffmpeg -f lavfi -i color=c=black:s=1080x1920:d=5 -i voice.mp3 -c:v libx264 -c:a aac -shortest {output_file} -y')
    
    print(f"Video {output_file} rendered successfully!")

if __name__ == '__main__':
    main()