import os
import json
import argparse
import google.generativeai as genai

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--channel", required=True)
    parser.add_argument("--format", choices=["short", "long"], default="short")
    args = parser.parse_args()
    
    # Load the channel configuration
    with open(f"channels/{args.channel}.json", "r") as f:
        config = json.load(f)
        
    print(f"Generating video for: {config['channel_id']}")
    
    # Connect to Gemini API
    genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
    model = genai.GenerativeModel('gemini-pro')
    
    print("Writing script...")
    script = model.generate_content(config["system_prompt"])
    
    print("Generating voiceover...")
    os.system('edge-tts --text "This is an automated short generated by AgentTube." --write-media voice.mp3')
    
    print("Rendering video with FFmpeg...")
    # Generates a 5-second vertical video combining a black background and the voiceover
    output_file = f"{args.channel}_output.mp4"
    os.system(f'ffmpeg -f lavfi -i color=c=black:s=1080x1920:d=5 -i voice.mp3 -c:v libx264 -c:a aac -shortest {output_file} -y')
    
    print(f"Video {output_file} rendered successfully!")

if __name__ == '__main__':
    main()